name: Publish and Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Publish .NET Core Project
        run: dotnet publish Hummer.csproj -c Release -o release -nologo

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
